version: '3.8'

# Services
services:
  # Server service
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: backend:latest
    container_name: backend
    ports:
      - "6001:6000"
    env_file: ./.env
    environment:
      - DB_HOST=mongodb_server
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    depends_on:
      - mongodb

  # Client service
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - server

  # Database Service
  mongodb:
    image: mongo:latest
    container_name: mongodb_server

    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

    ports:
      - "27017:27017"
    
    volumes:
      - ./../mydata:/data/db

# Volume define
volumes:
  mydata:

# MongoDB Client Service
  mongodb_client:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: mongo:latest
    container_name: mongodb_client
    command: ["sleep", "infinity"]  # Keep the container running indefinitely
    depends_on:
      - mongodb